version = 0.1

[default.deploy.parameters]
stack_name = "plane-tracker-flight-query"
resolve_s3 = true
s3_prefix = "plane-tracker-flight-query"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"tracker_log\" ApiKeyParam=\"/plane-tracker/api/key\" WindowMinutes=\"15\" MaxItems=\"50\" DefaultTimezone=\"America/Chicago\" StageName=\"prod\" ThrottleRateLimit=\"5\" ThrottleBurstLimit=\"10\" AllowedOrigins=\"https://flightlookup.tolfman.com\""
image_repositories = []

[default.global.parameters]
region = "us-east-2"
